### ISSUE TITLE
error when opening python files and linting incomplete

### ISSUE THREAD

**Issue by ToniDS** [python-mode/python-mode#980]
Dear everyone, 
I also now have the error "Errror detected while processing python/mode/pymode/lint.vim. 
Also, all my python files are shown as no errors or warnings found, despite there being many warnings. I'm using gvim on an Arch install, have the same problem on my server (also arch, but vim). 
I tried setting linter manually in .vimrc, no change. Any ideas?

This is the debug output:
```
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2019-01-07 13:48:24 with file /tmp/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Linux
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
  1: ~/.vim/pack/plugin/start/python-mode/debugvimrc.vim
  2: /usr/share/vim/vimfiles/plugin/SyntaxFolds.vim
  3: /usr/share/vim/vimfiles/plugin/filebrowser.vim
  4: /usr/share/vim/vimfiles/plugin/imaps.vim
  5: /usr/share/vim/vimfiles/plugin/remoteOpen.vim
  6: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
  7: /usr/share/vim/vim81/plugin/gzip.vim
  8: /usr/share/vim/vim81/plugin/logiPat.vim
  9: /usr/share/vim/vim81/plugin/manpager.vim
 10: /usr/share/vim/vim81/plugin/matchparen.vim
 11: /usr/share/vim/vim81/plugin/netrwPlugin.vim
 12: /usr/share/vim/vim81/plugin/rrhelper.vim
 13: /usr/share/vim/vim81/plugin/spellfile.vim
 14: /usr/share/vim/vim81/plugin/tarPlugin.vim
 15: /usr/share/vim/vim81/plugin/tohtml.vim
 16: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 17: /usr/share/vim/vim81/plugin/zipPlugin.vim
 18: ~/.vim/pack/plugin/start/python-mode/plugin/pymode.vim
 19: ~/.vim/pack/plugin/start/python-mode/autoload/pymode.vim
 20: /usr/share/vim/vim81/filetype.vim
 21: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
 22: /usr/share/vim/vimfiles/ftdetect/meson.vim
 23: /usr/share/vim/vimfiles/ftdetect/task.vim
 24: ~/.vim/pack/plugin/start/vim-jinja/ftdetect/jinja.vim
 25: ~/.vim/pack/plugin/start/ansible-vim/ftdetect/ansible.vim
 26: /usr/share/vim/vim81/ftplugin.vim
 27: ~/.vim/pack/plugin/start/nerdtree/plugin/NERD_tree.vim
 28: ~/.vim/pack/plugin/start/nerdtree/autoload/nerdtree.vim
 29: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/path.vim
 30: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/menu_controller.vim
 31: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/menu_item.vim
 32: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/key_map.vim
 33: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/bookmark.vimymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_preview_height #12
pymode_preview_position  botright
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
ac97c66a8b65a5811a67e4e6e326f4f6feb037d9
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo

Error detected while processing VimLeave Autocommands for "*.py":
E749: empty buffer
 34: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/tree_file_node.vim
 35: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/tree_dir_node.vim
 36: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/opener.vim
 37: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/creator.vim
 38: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/flag_set.vim
 39: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/nerdtree.vim
 40: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/ui.vim
 41: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/event.vim
 42: ~/.vim/pack/plugin/start/nerdtree/lib/nerdtree/notifier.vim
 43: ~/.vim/pack/plugin/start/nerdtree/autoload/nerdtree/ui_glue.vim
 44: ~/.vim/pack/plugin/start/nerdtree/nerdtree_plugin/exec_menuitem.vim
 45: ~/.vim/pack/plugin/start/nerdtree/nerdtree_plugin/fs_menu.vim
 46: ~/.vim/pack/plugin/start/nerdtree/nerdtree_plugin/vcs.vim
 47: ~/.vim/pack/plugin/start/syntastic/plugin/syntastic/autoloclist.vim
 48: ~/.vim/pack/plugin/start/syntastic/plugin/syntastic/balloons.vim
 49: ~/.vim/pack/plugin/start/syntastic/plugin/syntastic/checker.vim
 50: ~/.vim/pack/plugin/start/syntastic/plugin/syntastic/cursor.vim
 51: ~/.vim/pack/plugin/start/syntastic/plugin/syntastic/highlighting.vim
 52: ~/.vim/pack/plugin/start/syntastic/plugin/syntastic/loclist.vim
 53: ~/.vim/pack/plugin/start/syntastic/plugin/syntastic/modemap.vim
 54: ~/.vim/pack/plugin/start/syntastic/plugin/syntastic/notifiers.vim
 55: ~/.vim/pack/plugin/start/syntastic/plugin/syntastic/registry.vim
 56: ~/.vim/pack/plugin/start/syntastic/plugin/syntastic/signs.vim
 57: ~/.vim/pack/plugin/start/syntastic/plugin/syntastic.vim
 58: ~/.vim/pack/plugin/start/syntastic/autoload/syntastic/util.vim
 59: ~/.vim/pack/plugin/start/vim-latex/plugin/SyntaxFolds.vim
 60: ~/.vim/pack/plugin/start/vim-latex/plugin/filebrowser.vim
 61: ~/.vim/pack/plugin/start/vim-latex/plugin/imaps.vim
 62: ~/.vim/pack/plugin/start/vim-latex/plugin/remoteOpen.vim
 63: ~/.vim/pack/plugin/start/vim-latex-live-preview/plugin/latexlivepreview.vim
 64: ~/.vim/pack/plugin/start/syntastic/autoload/syntastic/log.vim
 65: /usr/share/vim/vim81/ftplugin/python.vim
 66: ~/.vim/pack/plugin/start/vim-flakes8/ftplugin/python_flake8.vim
 67: ~/.vim/pack/plugin/start/python-mode/ftplugin/python/pymode.vim
 68: ~/.vim/pack/plugin/start/python-mode/autoload/pymode/virtualenv.vim
 69: ~/.vim/pack/plugin/start/python-mode/autoload/pymode/breakpoint.vim
 70: ~/.vim/pack/plugin/start/python-mode/autoload/pymode/debug.vim
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /tmp/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II
pymode_lint_message   #1
pymode_lint_on_fly    #0
pymode_lint_on_write  #1
pymode_lint_options_mccabe {'complexity': 12}
pymode_lint_options_pep257 {}
pymode_lint_options_pep8 {'max_line_length': 79}
pymode_lint_options_pyflakes {'builtins': '_'}
pymode_lint_options_pylint {'max-line-length': 79}
pymode_lint_pyflakes_symbol  FF
pymode_lint_select    []
pymode_lint_signs     #1
pymode_lint_sort      []
pymode_lint_todo_symbol  WW
pymode_lint_unmodified #0
pymode_lint_visual_symbol  RR
pymode_motion         #1
pymode_options        #1
pymode_options_colorcolumn #1
pymode_options_max_line_length #79
pymode_paths          []
pymode_preview_height #12
pymode_preview_position  botright
pymode_python          python3
pymode_quickfix_maxheight #6
pymode_quickfix_minheight #3
pymode_rope           #0
pymode_run            #1
pymode_run_bind        <leader>r
pymode_trim_whitespaces #1
pymode_version         0.9.4
pymode_virtualenv     #1
pymode_virtualenv_enabled  
pymode_virtualenv_path  
pymode_warning        #1
-------------------------------------------------------------------------------
pymode debug msg 5: Git commit: 
ac97c66a8b65a5811a67e4e6e326f4f6feb037d9
-------------------------------------------------------------------------------
pymode debug msg 6: End of pymode#debug#sysinfo

Error detected while processing VimLeave Autocommands for "*.py":
E749: empty buffer

```

This is the output of vim --version: 
``
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  8 2018 11:23:48)
Included patches: 1-570
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +digraphs          +lispindent        +persistent_undo   +textobjects
+arabic            +dnd               +listcmds          +postscript        +timers
+autocmd           -ebcdic            +localmap          +printer           +title
+autochdir         +emacs_tags        +lua/dyn           +profile           +toolbar
-autoservername    +eval              +menu              +python/dyn        +user_commands
+balloon_eval      +ex_extra          +mksession         +python3/dyn       +vartabs
+balloon_eval_term +extra_search      +modify_fname      +quickfix          +vertsplit
+browse            +farsi             +mouse             +reltime           +virtualedit
++builtin_terms    +file_in_path      +mouseshape        +rightleft         +visual
+byte_offset       +find_in_path      +mouse_dec         +ruby/dyn          +visualextra
+channel           +float             +mouse_gpm         +scrollbind        +viminfo
+cindent           +folding           -mouse_jsbterm     +signs             +vreplace
+clientserver      -footer            +mouse_netterm     +smartindent       +wildignore
+clipboard         +fork()            +mouse_sgr         +startuptime       +wildmenu
+cmdline_compl     +gettext           -mouse_sysmouse    +statusline        +windows
+cmdline_hist      -hangul_input      +mouse_urxvt       -sun_workshop      +writebackup
+cmdline_info      +iconv             +mouse_xterm       +syntax            +X11
+comments          +insert_expand     +multi_byte        +tag_binary        -xfontset
+conceal           +job               +multi_lang        +tag_old_static    +xim
+cryptv            +jumplist          -mzscheme          -tag_any_white     -xpm
+cscope            +keymap            +netbeans_intg     +tcl/dyn           +xsmp_interact
+cursorbind        +lambda            +num64             +termguicolors     +xterm_clipboard
+cursorshape       +langmap           +packages          +terminal          -xterm_save
+dialog_con_gui    +libcall           +path_extra        +terminfo          
+diff              +linebreak         +perl/dyn          +termresponse      
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/libdrm -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -pthread  -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.28/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.28/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.28/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
```

**Comment by diraol** [comment]
Hi @ToniDS how did you installed python-mode?

Are all submodules updated?
And which python version are you using?

**Comment by ToniDS** [comment]
I'm using the package manager that comes with vim itself. Downloaded it using ansible. Here's my ansible script, for reference (which includes updating the submodules, unless I've made some sort of mistake...) - I've highlighted pythonmode.
I'm using python3. Have let g:pymode_python = 'python3' in my vimrc, no change.

```
# Installation
- name: Install vim on servers, else gvim
  pacman: 
    name: "{{ vim_pkg | default('gvim') }}" 
    state: latest
  become: yes 
  

 
# Configuration

- name: Create vimconfig
  template:
    src: vimrc.j2
    dest: ~/.vimrc
    backup: yes

- name: Create plugin manager directory
  file:
    path: "{{ plugin_dir }}"
    state: directory

- name: Install indentpython
  git: 
    repo: https://github.com/vim-scripts/indentpython.vim
    dest: "{{ plugin_dir }}/indentpython"
  register: indentpython
```
```
- name: Install python-mode
  git: 
    repo: https://github.com/python-mode/python-mode
    dest: "{{ plugin_dir }}/python-mode"
    recursive: yes
    track_submodules: yes
    force: yes
  register: python_mode
```
```
- name: Install vim-colors-solarized
  git: 
    repo: https://github.com/altercation/vim-colors-solarized
    dest: "{{ plugin_dir }}/vim-colors-solarized"
  register: solarized_colors

- name: Install syntastic
  git: 
    repo: https://github.com/vim-syntastic/syntastic
    dest: "{{ plugin_dir }}/syntastic"
  register: syntastic

- name: Install vim-flake8
  git: 
    repo: https://github.com/nvie/vim-flake8
    dest: "{{ plugin_dir }}/vim-flakes8"
  register: flake8

- name: Install vim-jinjia
  git: 
    repo: https://github.com/lepture/vim-jinja
    dest: "{{ plugin_dir }}/vim-jinja"
  register: jinja

- name: Install nerdtree
  git: 
    repo: https://github.com/scrooloose/nerdtree
    dest: "{{ plugin_dir }}/nerdtree"
  register: nerdtree

- name: Install ansible-vim
  git: 
    repo: https://github.com/pearofducks/ansible-vim
    dest: "{{ plugin_dir }}/ansible-vim"
  register: ansible_vim

- name: Install zenburn
  git: 
    repo: https://github.com/jnurmine/Zenburn 
    dest: "{{ plugin_dir }}/Zenburn"
  register: zenburn_vim

- name: Install vim-latex
  git: 
    repo: https://github.com/vim-latex/vim-latex
    dest: "{{ plugin_dir }}/vim-latex"
  register: latex_vim
  #- name: Install youcompleteme/Omnicomplete

- name: Install live-preview-latex
  git: 
    repo: https://github.com/xuhdev/vim-latex-live-preview
    dest: "{{ plugin_dir }}/vim-latex-live-preview"
  register: latex_live_vim
```
